import {endpoint,body,sameOrigin,bindings,fail,hash,id,now,limit,json} from '../../../lib/server';
import {passwordHash,passwordMatches,session,turnstile} from '../../../lib/auth';
export const POST=endpoint(async ctx=>{
 sameOrigin(ctx.request);const action=ctx.params.action;const d=await body(ctx.request);const e=bindings();const email=String(d.email||'').trim().toLowerCase();const password=String(d.password||'');
 await limit(`auth:${action}:${ctx.request.headers.get('cf-connecting-ip')||'local'}`,20,600);
 if(action==='logout'){const token=ctx.cookies.get('obraz_session')?.value;if(token)await e.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(token)).run();ctx.cookies.delete('obraz_session',{path:'/'});return json({ok:true});}
 if(action==='reset'){if(password.length<12||password.length>128)fail(400,'Паролата трябва да е между 12 и 128 символа.');const tokenHash=await hash(String(d.token||''));const token=await e.DB.prepare('SELECT user_id FROM reset_tokens WHERE token_hash=? AND expires_at>?').bind(tokenHash,now()).first<{user_id:string}>();if(!token)fail(400,'Линкът е изтекъл или вече е използван.');const p=await passwordHash(password);const r=await e.DB.batch([e.DB.prepare('UPDATE users SET password_hash=? WHERE id=? AND EXISTS(SELECT 1 FROM reset_tokens WHERE token_hash=? AND expires_at>?)').bind(p,token.user_id,tokenHash,now()),e.DB.prepare('DELETE FROM reset_tokens WHERE user_id=?').bind(token.user_id),e.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(token.user_id)]);if(!r[0].meta.changes)fail(400,'Линкът вече е използван.');return json({ok:true});}
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)fail(400,'Въведете валиден имейл.');
 await limit(`email:${action}:${email}`,8,600);
 if(action==='forgot'){await turnstile(ctx,d.turnstile);if(!e.RESEND_API_KEY||!e.EMAIL_FROM||!e.SITE_URL)fail(503,'Възстановяването на парола още не е активирано.');const u=await e.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first<{id:string}>();if(u){const token=id()+id();await e.DB.prepare('INSERT INTO reset_tokens VALUES (?,?,?)').bind(await hash(token),u.id,now()+1800).run();const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${e.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:e.EMAIL_FROM,to:email,subject:'Нова парола за Образ',text:`Задайте нова парола до 30 минути: ${e.SITE_URL}/reset?token=${token}\nАко не сте поискали промяната, игнорирайте този имейл.`})});if(!r.ok)fail(503,'Имейлът не може да бъде изпратен в момента.');}return json({ok:true,message:'Ако има профил с този имейл, ще получите линк за нова парола.'});}
 if(action==='register'){if(e.REGISTRATION_ENABLED!=='true')fail(403,'Регистрацията временно е затворена.');await turnstile(ctx,d.turnstile);if(password.length<12||password.length>128)fail(400,'Използвайте парола между 12 и 128 символа.');const name=String(d.name||'').trim();if(name.length<2||name.length>80||d.terms!==true)fail(400,'Въведете име и приемете условията.');const uid=id();const p=await passwordHash(password);const r=await e.DB.prepare('INSERT OR IGNORE INTO users(id,email,name,password_hash,created_at) VALUES (?,?,?,?,?)').bind(uid,email,name,p,now()).run();if(!r.meta.changes)fail(409,'Вече има профил с този имейл.');await session(ctx,uid);return json({ok:true});}
 if(action==='login'){if(password.length>128)fail(400,'Невалидни данни.');const u=await e.DB.prepare('SELECT id,password_hash FROM users WHERE email=?').bind(email).first<{id:string;password_hash:string}>();const valid=await passwordMatches(password,u?.password_hash||'00000000-0000-0000-0000-000000000000:'+ '0'.repeat(64));if(!u||!valid)fail(401,'Грешен имейл или парола.');await session(ctx,u.id);return json({ok:true});}
 fail(404,'Страницата не е намерена.');
});
