import {endpoint,sameOrigin,body,bindings,requireUser,fail,id,now,json,limit} from '../../lib/server';
import {MODELS,STYLES,MAX_IMAGE_BYTES,type ModelKey} from '../../lib/catalog';
import {imageOutput} from '../../lib/image-output';
export const POST=endpoint(async ctx=>{
 sameOrigin(ctx.request);const u=await requireUser(ctx);await limit(`generate:${u.id}`,30,60);if(u.period_end && u.period_end<=now())fail(402,'Абонаментът е изтекъл. Подновете го от профила си.');const d=await body(ctx.request);const model=String(d.model||'klein') as ModelKey;if(!Object.hasOwn(MODELS,model))fail(400,'Изберете валиден модел.');const style=String(d.style||'none') as keyof typeof STYLES;if(!Object.hasOwn(STYLES,style))fail(400,'Невалиден стил.');const prompt=String(d.prompt||'').trim();if(prompt.length<3||prompt.length>1500)fail(400,'Описанието трябва да е между 3 и 1500 символа.');const requestKey=String(d.requestKey||'');if(!/^[a-zA-Z0-9-]{16,80}$/.test(requestKey))fail(400,'Невалиден идентификатор на заявката.');const e=bindings();const previous=await e.DB.prepare('SELECT id,status FROM images WHERE user_id=? AND request_key=?').bind(u.id,requestKey).first();if(previous)return json(previous,202);
 const imageId=id();const key=`${u.id}/${imageId}`;const m=MODELS[model];if(m.thirdParty&&!e.AI_GATEWAY_ID)fail(503,'Този модел още не е активиран. Изберете FLUX.');const reservation=e.DB.prepare("INSERT INTO images(id,user_id,request_key,prompt,style,model,cost,key,created_at) SELECT ?,?,?,?,?,?,?,?,? FROM users WHERE id=? AND credits>=? AND storage_used+storage_reserved+?<=storage_limit AND (SELECT COUNT(*) FROM images WHERE user_id=? AND status='pending')<2").bind(imageId,u.id,requestKey,prompt,style,model,m.credits,key,now(),u.id,m.credits,MAX_IMAGE_BYTES,u.id);let changed=0;try{changed=(await reservation.run()).meta.changes;}catch(error){const duplicate=await e.DB.prepare('SELECT id,status FROM images WHERE user_id=? AND request_key=?').bind(u.id,requestKey).first();if(duplicate)return json(duplicate,202);throw error;}if(!changed)fail(402,'Недостатъчни кредити, запълнена библиотека или две активни заявки.');
 try{let input:Record<string,unknown>={prompt:`${prompt}\n${STYLES[style]}`,...m.input};if(m.multipart){const form=new FormData();form.set('prompt',`${prompt}\n${STYLES[style]}`);form.set('width','1024');form.set('height','1024');const resp=new Response(form);input={multipart:{body:resp.body,contentType:resp.headers.get('content-type')}};}
 const output=await e.AI.run(m.id as Parameters<Ai['run']>[0],input as never,m.thirdParty?{gateway:{id:e.AI_GATEWAY_ID!}}:undefined);
 const {bytes,mime}=await imageOutput(output,e.IMAGE_RESULT_HOSTS||'examples.aig.cloudflare.com,*.r2.dev');await e.IMAGES.put(key,bytes,{httpMetadata:{contentType:mime}});const saved=await e.DB.prepare("UPDATE images SET status='complete',bytes=?,mime=? WHERE id=? AND status='pending'").bind(bytes.byteLength,mime,imageId).run();if(!saved.meta.changes){await e.IMAGES.delete(key);throw new Error('Generation was cancelled');}return json({id:imageId,status:'complete',url:`/api/images/${imageId}`,credits:u.credits-m.credits});
 }catch(error){const state=await e.DB.prepare('SELECT status FROM images WHERE id=?').bind(imageId).first<{status:string}>().catch(()=>null);if(state?.status==='complete')return json({id:imageId,status:'complete',url:`/api/images/${imageId}`});console.error('Generation failed',model,error instanceof Error?error.message:'unknown');await e.IMAGES.delete(key).catch(()=>{});await e.DB.prepare("UPDATE images SET status='failed' WHERE id=? AND status='pending'").bind(imageId).run();fail(502,'Изображението не беше създадено. Кредитите са възстановени.');}
});
